### ISSUE TITLE
Make the hephy-router image smaller

### ISSUE THREAD

**Issue by Cryptophobia** [teamhephy/router#27]
The Docker image runs at 674MB because of Modsecurity and Tcell dynamic modules. We should look at lowering the size of the container by maybe using multi-stage Docker builds or flattening the layers of the Docker image as the last resort.

**Comment by kingdonb** [comment]
The technique used in BaseImage (Ubuntu/Phusion) to make the image smaller is to take everything and put it into a script.  This way you can have a readable Dockerfile without a ton of

```
RUN apt-get -y --no-install-recommends huge-list of-packages \
  some-more-packages \
  way-too-many-lines-of-code \
  in-a-single-run-directive \
  && do-the-build-things \
  && apt-get remove --purge all-of-those-things
```

https://github.com/phusion/baseimage-docker/blob/master/image/Dockerfile

Instead you get something like:

```
RUN /bd_build/prepare.sh && \
	/bd_build/system_services.sh && \
	/bd_build/utilities.sh && \
	/bd_build/cleanup.sh
```

**Comment by Cryptophobia** [comment]
Yes, we are already appending all RUN instructions to each other in the image so that they will create one layer. ;)

I think if we do a docker-squash now and merge some of the unnecessary layers like the `chown` and `add` files layers, we should be able to save around 10-40% space but I think the image is still maintainable in the current state. I am begin to get more worried if we keep adding features to the router. Modsecurity was what really increased the size of this image.

I usually use the [docker-squash](https://github.com/goldmann/docker-squash) python package do the squashing of the layers. I can test it out with this image and see the improvement.

**Comment by Cryptophobia** [comment]
This has improved a lot since moving to multi-stage build thanks to work by @felixbuenemann ! Compressed size is about 100mb on docker hub. I think it's okay to close this issue for now.

```
docker images
REPOSITORY     TAG           IMAGE ID       CREATED          SIZE
hephy/router   canary        e08db7bc9b04   30 minutes ago   247MB
hephy/router   git-2c6f6f6   e08db7bc9b04   30 minutes ago   247MB
```
